--------------------------------------------------------
--  File created - четвъртък-февруари-29-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIES
--------------------------------------------------------

  CREATE TABLE "C##EX23_MARTIN_COURSETASK"."CATEGORIES" OF "C##EX23_MARTIN_COURSETASK"."CATEGORY_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MANUFACTURERS
--------------------------------------------------------

  CREATE TABLE "C##EX23_MARTIN_COURSETASK"."MANUFACTURERS" OF "C##EX23_MARTIN_COURSETASK"."MANUFACTURER_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERPRODUCTS
--------------------------------------------------------

  CREATE TABLE "C##EX23_MARTIN_COURSETASK"."ORDERPRODUCTS" OF "C##EX23_MARTIN_COURSETASK"."ORDER_PRODUCT_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "C##EX23_MARTIN_COURSETASK"."ORDERS" OF "C##EX23_MARTIN_COURSETASK"."ORDER_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "C##EX23_MARTIN_COURSETASK"."PRODUCTS" OF "C##EX23_MARTIN_COURSETASK"."PRODUCT_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROMOCODES
--------------------------------------------------------

  CREATE TABLE "C##EX23_MARTIN_COURSETASK"."PROMOCODES" OF "C##EX23_MARTIN_COURSETASK"."PROMOCODE_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##EX23_MARTIN_COURSETASK"."USERS" OF "C##EX23_MARTIN_COURSETASK"."USER_T" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EX23_MARTIN_COURSETASK.CATEGORIES
SET DEFINE OFF;
Insert into C##EX23_MARTIN_COURSETASK.CATEGORIES (CATEGORYID,CATEGORYNAME) values (1,'Components');
Insert into C##EX23_MARTIN_COURSETASK.CATEGORIES (CATEGORYID,CATEGORYNAME) values (2,'Peripherals');
REM INSERTING into C##EX23_MARTIN_COURSETASK.MANUFACTURERS
SET DEFINE OFF;
Insert into C##EX23_MARTIN_COURSETASK.MANUFACTURERS (MANUFACTURERID,MANUFACTURERNAME,COUNTRY) values (2,'Intel','USA');
Insert into C##EX23_MARTIN_COURSETASK.MANUFACTURERS (MANUFACTURERID,MANUFACTURERNAME,COUNTRY) values (3,'Logitech','USA');
Insert into C##EX23_MARTIN_COURSETASK.MANUFACTURERS (MANUFACTURERID,MANUFACTURERNAME,COUNTRY) values (4,'Asrock','USA');
Insert into C##EX23_MARTIN_COURSETASK.MANUFACTURERS (MANUFACTURERID,MANUFACTURERNAME,COUNTRY) values (5,'AOC','USA');
Insert into C##EX23_MARTIN_COURSETASK.MANUFACTURERS (MANUFACTURERID,MANUFACTURERNAME,COUNTRY) values (1,'AMD','USA');
REM INSERTING into C##EX23_MARTIN_COURSETASK.ORDERPRODUCTS
SET DEFINE OFF;
Insert into C##EX23_MARTIN_COURSETASK.ORDERPRODUCTS (ORDERID,PRODUCTID,ORDEREDQUANTITY,SUBTOTAL) values (1,2,1,129.99);
REM INSERTING into C##EX23_MARTIN_COURSETASK.ORDERS
SET DEFINE OFF;
Insert into C##EX23_MARTIN_COURSETASK.ORDERS (ORDERID,ORDERSTATUS,ORDEREDQUANTITY,TOTALPRICE,ORDEREDON,CUSTOMER,PROMOCODE,FINANCIALOBLIGATION) values (1,'Pending',2,129.99,'2024-02-24',C##EX23_MARTIN_COURSETASK.USER_T(3, 'Alice Johnson', 'alice@example.com', '123456', '24.02.2024'),C##EX23_MARTIN_COURSETASK.PROMOCODE_T(1, 'MSD10', 10, '25.02.2024', '29.02.2024'),C##EX23_MARTIN_COURSETASK.FINANCIAL_OBLIGATION_T(1, 'CrCard', 'Pending', 249.99, 0, NULL));
REM INSERTING into C##EX23_MARTIN_COURSETASK.PRODUCTS
SET DEFINE OFF;
Insert into C##EX23_MARTIN_COURSETASK.PRODUCTS (PRODUCTID,PRODUCTNAME,MODELNAME,MANUFACTURER,PRICE,PRODUCTCATEGORY,ADDEDON) values (1,'Intel Core i7','i7-10700K',C##EX23_MARTIN_COURSETASK.MANUFACTURER_T(2, 'Intel', 'USA'),399.99,C##EX23_MARTIN_COURSETASK.CATEGORY_T(1, 'Components'),'24.02.2024');
Insert into C##EX23_MARTIN_COURSETASK.PRODUCTS (PRODUCTID,PRODUCTNAME,MODELNAME,MANUFACTURER,PRICE,PRODUCTCATEGORY,ADDEDON) values (2,'ASRock','B550M Pro4',C##EX23_MARTIN_COURSETASK.MANUFACTURER_T(4, 'Asrock', 'USA'),129.99,C##EX23_MARTIN_COURSETASK.CATEGORY_T(1, 'Components'),'24.02.2024');
Insert into C##EX23_MARTIN_COURSETASK.PRODUCTS (PRODUCTID,PRODUCTNAME,MODELNAME,MANUFACTURER,PRICE,PRODUCTCATEGORY,ADDEDON) values (3,'G Pro X','G Pro X',C##EX23_MARTIN_COURSETASK.MANUFACTURER_T(3, 'Logitech', 'USA'),149.99,C##EX23_MARTIN_COURSETASK.CATEGORY_T(2, 'Peripherals'),'24.02.2024');
Insert into C##EX23_MARTIN_COURSETASK.PRODUCTS (PRODUCTID,PRODUCTNAME,MODELNAME,MANUFACTURER,PRICE,PRODUCTCATEGORY,ADDEDON) values (4,'AOC','CQ32G1',C##EX23_MARTIN_COURSETASK.MANUFACTURER_T(5, 'AOC', 'USA'),299.99,C##EX23_MARTIN_COURSETASK.CATEGORY_T(2, 'Peripherals'),'24.02.2024');
REM INSERTING into C##EX23_MARTIN_COURSETASK.PROMOCODES
SET DEFINE OFF;
Insert into C##EX23_MARTIN_COURSETASK.PROMOCODES (PROMOCODEID,PROMOCODENAME,DISCOUNTPERCENTAGE,STARTDATE,ENDDATE) values (1,'MSD10',10,'25.02.2024','29.02.2024');
Insert into C##EX23_MARTIN_COURSETASK.PROMOCODES (PROMOCODEID,PROMOCODENAME,DISCOUNTPERCENTAGE,STARTDATE,ENDDATE) values (2,'MSD25',25,'2024-02-01','2024-02-29');
Insert into C##EX23_MARTIN_COURSETASK.PROMOCODES (PROMOCODEID,PROMOCODENAME,DISCOUNTPERCENTAGE,STARTDATE,ENDDATE) values (3,'MSD30',30,'2024-02-01','2024-02-29');
REM INSERTING into C##EX23_MARTIN_COURSETASK.USERS
SET DEFINE OFF;
Insert into C##EX23_MARTIN_COURSETASK.USERS (USERID,USERNAMES,EMAIL,USERPASSWORD,CREATEDON) values (3,'Alice Johnson','alice@example.com','123456','24.02.2024');
Insert into C##EX23_MARTIN_COURSETASK.USERS (USERID,USERNAMES,EMAIL,USERPASSWORD,CREATEDON) values (4,'Bob Miller','bob@example.com','789101112','24.02.2024');
Insert into C##EX23_MARTIN_COURSETASK.USERS (USERID,USERNAMES,EMAIL,USERPASSWORD,CREATEDON) values (1,'John Doe','john@example.com','654321','24.02.2024');
Insert into C##EX23_MARTIN_COURSETASK.USERS (USERID,USERNAMES,EMAIL,USERPASSWORD,CREATEDON) values (2,'Jane Smith','jane@example.com','010300','26.02.2024');
Insert into C##EX23_MARTIN_COURSETASK.USERS (USERID,USERNAMES,EMAIL,USERPASSWORD,CREATEDON) values (5,'asd','sad','asd','27.02.2024');
--------------------------------------------------------
--  DDL for Index SYS_C0029341
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EX23_MARTIN_COURSETASK"."SYS_C0029341" ON "C##EX23_MARTIN_COURSETASK"."CATEGORIES" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0029342
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EX23_MARTIN_COURSETASK"."SYS_C0029342" ON "C##EX23_MARTIN_COURSETASK"."MANUFACTURERS" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0029391
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EX23_MARTIN_COURSETASK"."SYS_C0029391" ON "C##EX23_MARTIN_COURSETASK"."ORDERPRODUCTS" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0029392
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EX23_MARTIN_COURSETASK"."SYS_C0029392" ON "C##EX23_MARTIN_COURSETASK"."ORDERS" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0029344
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EX23_MARTIN_COURSETASK"."SYS_C0029344" ON "C##EX23_MARTIN_COURSETASK"."PRODUCTS" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0029340
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EX23_MARTIN_COURSETASK"."SYS_C0029340" ON "C##EX23_MARTIN_COURSETASK"."PROMOCODES" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0029339
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EX23_MARTIN_COURSETASK"."SYS_C0029339" ON "C##EX23_MARTIN_COURSETASK"."USERS" ("SYS_NC_OID$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CATEGORIES
--------------------------------------------------------

  ALTER TABLE "C##EX23_MARTIN_COURSETASK"."CATEGORIES" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANUFACTURERS
--------------------------------------------------------

  ALTER TABLE "C##EX23_MARTIN_COURSETASK"."MANUFACTURERS" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERPRODUCTS
--------------------------------------------------------

  ALTER TABLE "C##EX23_MARTIN_COURSETASK"."ORDERPRODUCTS" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##EX23_MARTIN_COURSETASK"."ORDERS" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "C##EX23_MARTIN_COURSETASK"."PRODUCTS" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROMOCODES
--------------------------------------------------------

  ALTER TABLE "C##EX23_MARTIN_COURSETASK"."PROMOCODES" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##EX23_MARTIN_COURSETASK"."USERS" ADD UNIQUE ("SYS_NC_OID$")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
